name: aoc-cron
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -o aoc .

      - name: Run
        run: ./aoc
        env:
          googleChatKey: ${{ secrets.GOOGLE_CHAT_KEY }}
          googleChatToken: ${{ secrets.GOOGLE_CHAT_TOKEN }}
          sessionCookie: ${{ secrets.SESSION_COOKIE }}